package cn.xvkang.netty.protocolbuffer;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ZhMessage.proto

public final class ZhMessageProto {
  private ZhMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ZhMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ZhMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string whoami = 1;</code>
     */
    boolean hasWhoami();
    /**
     * <code>required string whoami = 1;</code>
     */
    java.lang.String getWhoami();
    /**
     * <code>required string whoami = 1;</code>
     */
    com.google.protobuf.ByteString
        getWhoamiBytes();

    /**
     * <code>required string contenttype = 2;</code>
     */
    boolean hasContenttype();
    /**
     * <code>required string contenttype = 2;</code>
     */
    java.lang.String getContenttype();
    /**
     * <code>required string contenttype = 2;</code>
     */
    com.google.protobuf.ByteString
        getContenttypeBytes();

    /**
     * <code>optional string contentstring = 3;</code>
     */
    boolean hasContentstring();
    /**
     * <code>optional string contentstring = 3;</code>
     */
    java.lang.String getContentstring();
    /**
     * <code>optional string contentstring = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentstringBytes();

    /**
     * <code>optional bytes contentfile = 4;</code>
     */
    boolean hasContentfile();
    /**
     * <code>optional bytes contentfile = 4;</code>
     */
    com.google.protobuf.ByteString getContentfile();

    /**
     * <code>optional string contentfilename = 5;</code>
     */
    boolean hasContentfilename();
    /**
     * <code>optional string contentfilename = 5;</code>
     */
    java.lang.String getContentfilename();
    /**
     * <code>optional string contentfilename = 5;</code>
     */
    com.google.protobuf.ByteString
        getContentfilenameBytes();

    /**
     * <code>optional string whichphonelocation = 6;</code>
     */
    boolean hasWhichphonelocation();
    /**
     * <code>optional string whichphonelocation = 6;</code>
     */
    java.lang.String getWhichphonelocation();
    /**
     * <code>optional string whichphonelocation = 6;</code>
     */
    com.google.protobuf.ByteString
        getWhichphonelocationBytes();

    /**
     * <code>optional string sendtowhichpc = 7;</code>
     */
    boolean hasSendtowhichpc();
    /**
     * <code>optional string sendtowhichpc = 7;</code>
     */
    java.lang.String getSendtowhichpc();
    /**
     * <code>optional string sendtowhichpc = 7;</code>
     */
    com.google.protobuf.ByteString
        getSendtowhichpcBytes();

    /**
     * <code>optional string locationstring = 8;</code>
     */
    boolean hasLocationstring();
    /**
     * <code>optional string locationstring = 8;</code>
     */
    java.lang.String getLocationstring();
    /**
     * <code>optional string locationstring = 8;</code>
     */
    com.google.protobuf.ByteString
        getLocationstringBytes();
  }
  /**
   * Protobuf type {@code ZhMessage}
   */
  public  static final class ZhMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ZhMessage)
      ZhMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ZhMessage.newBuilder() to construct.
    private ZhMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ZhMessage() {
      whoami_ = "";
      contenttype_ = "";
      contentstring_ = "";
      contentfile_ = com.google.protobuf.ByteString.EMPTY;
      contentfilename_ = "";
      whichphonelocation_ = "";
      sendtowhichpc_ = "";
      locationstring_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ZhMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              whoami_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              contenttype_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              contentstring_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              contentfile_ = input.readBytes();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              contentfilename_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              whichphonelocation_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              sendtowhichpc_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              locationstring_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ZhMessageProto.internal_static_ZhMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ZhMessageProto.internal_static_ZhMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ZhMessageProto.ZhMessage.class, ZhMessageProto.ZhMessage.Builder.class);
    }

    private int bitField0_;
    public static final int WHOAMI_FIELD_NUMBER = 1;
    private volatile java.lang.Object whoami_;
    /**
     * <code>required string whoami = 1;</code>
     */
    public boolean hasWhoami() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string whoami = 1;</code>
     */
    public java.lang.String getWhoami() {
      java.lang.Object ref = whoami_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          whoami_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string whoami = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWhoamiBytes() {
      java.lang.Object ref = whoami_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        whoami_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object contenttype_;
    /**
     * <code>required string contenttype = 2;</code>
     */
    public boolean hasContenttype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string contenttype = 2;</code>
     */
    public java.lang.String getContenttype() {
      java.lang.Object ref = contenttype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contenttype_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string contenttype = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContenttypeBytes() {
      java.lang.Object ref = contenttype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contenttype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTSTRING_FIELD_NUMBER = 3;
    private volatile java.lang.Object contentstring_;
    /**
     * <code>optional string contentstring = 3;</code>
     */
    public boolean hasContentstring() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string contentstring = 3;</code>
     */
    public java.lang.String getContentstring() {
      java.lang.Object ref = contentstring_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contentstring_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string contentstring = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentstringBytes() {
      java.lang.Object ref = contentstring_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentstring_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTFILE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString contentfile_;
    /**
     * <code>optional bytes contentfile = 4;</code>
     */
    public boolean hasContentfile() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes contentfile = 4;</code>
     */
    public com.google.protobuf.ByteString getContentfile() {
      return contentfile_;
    }

    public static final int CONTENTFILENAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object contentfilename_;
    /**
     * <code>optional string contentfilename = 5;</code>
     */
    public boolean hasContentfilename() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string contentfilename = 5;</code>
     */
    public java.lang.String getContentfilename() {
      java.lang.Object ref = contentfilename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contentfilename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string contentfilename = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContentfilenameBytes() {
      java.lang.Object ref = contentfilename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentfilename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WHICHPHONELOCATION_FIELD_NUMBER = 6;
    private volatile java.lang.Object whichphonelocation_;
    /**
     * <code>optional string whichphonelocation = 6;</code>
     */
    public boolean hasWhichphonelocation() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string whichphonelocation = 6;</code>
     */
    public java.lang.String getWhichphonelocation() {
      java.lang.Object ref = whichphonelocation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          whichphonelocation_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string whichphonelocation = 6;</code>
     */
    public com.google.protobuf.ByteString
        getWhichphonelocationBytes() {
      java.lang.Object ref = whichphonelocation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        whichphonelocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTOWHICHPC_FIELD_NUMBER = 7;
    private volatile java.lang.Object sendtowhichpc_;
    /**
     * <code>optional string sendtowhichpc = 7;</code>
     */
    public boolean hasSendtowhichpc() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string sendtowhichpc = 7;</code>
     */
    public java.lang.String getSendtowhichpc() {
      java.lang.Object ref = sendtowhichpc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sendtowhichpc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sendtowhichpc = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSendtowhichpcBytes() {
      java.lang.Object ref = sendtowhichpc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendtowhichpc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATIONSTRING_FIELD_NUMBER = 8;
    private volatile java.lang.Object locationstring_;
    /**
     * <code>optional string locationstring = 8;</code>
     */
    public boolean hasLocationstring() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string locationstring = 8;</code>
     */
    public java.lang.String getLocationstring() {
      java.lang.Object ref = locationstring_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          locationstring_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string locationstring = 8;</code>
     */
    public com.google.protobuf.ByteString
        getLocationstringBytes() {
      java.lang.Object ref = locationstring_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locationstring_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasWhoami()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContenttype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, whoami_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contenttype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, contentstring_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, contentfile_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, contentfilename_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, whichphonelocation_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sendtowhichpc_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, locationstring_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, whoami_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contenttype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, contentstring_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, contentfile_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, contentfilename_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, whichphonelocation_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sendtowhichpc_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, locationstring_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ZhMessageProto.ZhMessage)) {
        return super.equals(obj);
      }
      ZhMessageProto.ZhMessage other = (ZhMessageProto.ZhMessage) obj;

      boolean result = true;
      result = result && (hasWhoami() == other.hasWhoami());
      if (hasWhoami()) {
        result = result && getWhoami()
            .equals(other.getWhoami());
      }
      result = result && (hasContenttype() == other.hasContenttype());
      if (hasContenttype()) {
        result = result && getContenttype()
            .equals(other.getContenttype());
      }
      result = result && (hasContentstring() == other.hasContentstring());
      if (hasContentstring()) {
        result = result && getContentstring()
            .equals(other.getContentstring());
      }
      result = result && (hasContentfile() == other.hasContentfile());
      if (hasContentfile()) {
        result = result && getContentfile()
            .equals(other.getContentfile());
      }
      result = result && (hasContentfilename() == other.hasContentfilename());
      if (hasContentfilename()) {
        result = result && getContentfilename()
            .equals(other.getContentfilename());
      }
      result = result && (hasWhichphonelocation() == other.hasWhichphonelocation());
      if (hasWhichphonelocation()) {
        result = result && getWhichphonelocation()
            .equals(other.getWhichphonelocation());
      }
      result = result && (hasSendtowhichpc() == other.hasSendtowhichpc());
      if (hasSendtowhichpc()) {
        result = result && getSendtowhichpc()
            .equals(other.getSendtowhichpc());
      }
      result = result && (hasLocationstring() == other.hasLocationstring());
      if (hasLocationstring()) {
        result = result && getLocationstring()
            .equals(other.getLocationstring());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasWhoami()) {
        hash = (37 * hash) + WHOAMI_FIELD_NUMBER;
        hash = (53 * hash) + getWhoami().hashCode();
      }
      if (hasContenttype()) {
        hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getContenttype().hashCode();
      }
      if (hasContentstring()) {
        hash = (37 * hash) + CONTENTSTRING_FIELD_NUMBER;
        hash = (53 * hash) + getContentstring().hashCode();
      }
      if (hasContentfile()) {
        hash = (37 * hash) + CONTENTFILE_FIELD_NUMBER;
        hash = (53 * hash) + getContentfile().hashCode();
      }
      if (hasContentfilename()) {
        hash = (37 * hash) + CONTENTFILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getContentfilename().hashCode();
      }
      if (hasWhichphonelocation()) {
        hash = (37 * hash) + WHICHPHONELOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getWhichphonelocation().hashCode();
      }
      if (hasSendtowhichpc()) {
        hash = (37 * hash) + SENDTOWHICHPC_FIELD_NUMBER;
        hash = (53 * hash) + getSendtowhichpc().hashCode();
      }
      if (hasLocationstring()) {
        hash = (37 * hash) + LOCATIONSTRING_FIELD_NUMBER;
        hash = (53 * hash) + getLocationstring().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ZhMessageProto.ZhMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ZhMessageProto.ZhMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ZhMessageProto.ZhMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ZhMessageProto.ZhMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ZhMessageProto.ZhMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ZhMessageProto.ZhMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ZhMessageProto.ZhMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ZhMessageProto.ZhMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ZhMessageProto.ZhMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ZhMessageProto.ZhMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ZhMessageProto.ZhMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ZhMessageProto.ZhMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ZhMessageProto.ZhMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ZhMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ZhMessage)
        ZhMessageProto.ZhMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ZhMessageProto.internal_static_ZhMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ZhMessageProto.internal_static_ZhMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ZhMessageProto.ZhMessage.class, ZhMessageProto.ZhMessage.Builder.class);
      }

      // Construct using ZhMessageProto.ZhMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        whoami_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        contenttype_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        contentstring_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        contentfile_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        contentfilename_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        whichphonelocation_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        sendtowhichpc_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        locationstring_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ZhMessageProto.internal_static_ZhMessage_descriptor;
      }

      public ZhMessageProto.ZhMessage getDefaultInstanceForType() {
        return ZhMessageProto.ZhMessage.getDefaultInstance();
      }

      public ZhMessageProto.ZhMessage build() {
        ZhMessageProto.ZhMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ZhMessageProto.ZhMessage buildPartial() {
        ZhMessageProto.ZhMessage result = new ZhMessageProto.ZhMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.whoami_ = whoami_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.contenttype_ = contenttype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.contentstring_ = contentstring_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.contentfile_ = contentfile_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.contentfilename_ = contentfilename_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.whichphonelocation_ = whichphonelocation_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.sendtowhichpc_ = sendtowhichpc_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.locationstring_ = locationstring_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ZhMessageProto.ZhMessage) {
          return mergeFrom((ZhMessageProto.ZhMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ZhMessageProto.ZhMessage other) {
        if (other == ZhMessageProto.ZhMessage.getDefaultInstance()) return this;
        if (other.hasWhoami()) {
          bitField0_ |= 0x00000001;
          whoami_ = other.whoami_;
          onChanged();
        }
        if (other.hasContenttype()) {
          bitField0_ |= 0x00000002;
          contenttype_ = other.contenttype_;
          onChanged();
        }
        if (other.hasContentstring()) {
          bitField0_ |= 0x00000004;
          contentstring_ = other.contentstring_;
          onChanged();
        }
        if (other.hasContentfile()) {
          setContentfile(other.getContentfile());
        }
        if (other.hasContentfilename()) {
          bitField0_ |= 0x00000010;
          contentfilename_ = other.contentfilename_;
          onChanged();
        }
        if (other.hasWhichphonelocation()) {
          bitField0_ |= 0x00000020;
          whichphonelocation_ = other.whichphonelocation_;
          onChanged();
        }
        if (other.hasSendtowhichpc()) {
          bitField0_ |= 0x00000040;
          sendtowhichpc_ = other.sendtowhichpc_;
          onChanged();
        }
        if (other.hasLocationstring()) {
          bitField0_ |= 0x00000080;
          locationstring_ = other.locationstring_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWhoami()) {
          return false;
        }
        if (!hasContenttype()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ZhMessageProto.ZhMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ZhMessageProto.ZhMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object whoami_ = "";
      /**
       * <code>required string whoami = 1;</code>
       */
      public boolean hasWhoami() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string whoami = 1;</code>
       */
      public java.lang.String getWhoami() {
        java.lang.Object ref = whoami_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            whoami_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string whoami = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWhoamiBytes() {
        java.lang.Object ref = whoami_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          whoami_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string whoami = 1;</code>
       */
      public Builder setWhoami(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        whoami_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string whoami = 1;</code>
       */
      public Builder clearWhoami() {
        bitField0_ = (bitField0_ & ~0x00000001);
        whoami_ = getDefaultInstance().getWhoami();
        onChanged();
        return this;
      }
      /**
       * <code>required string whoami = 1;</code>
       */
      public Builder setWhoamiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        whoami_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contenttype_ = "";
      /**
       * <code>required string contenttype = 2;</code>
       */
      public boolean hasContenttype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string contenttype = 2;</code>
       */
      public java.lang.String getContenttype() {
        java.lang.Object ref = contenttype_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            contenttype_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string contenttype = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContenttypeBytes() {
        java.lang.Object ref = contenttype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contenttype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string contenttype = 2;</code>
       */
      public Builder setContenttype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        contenttype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string contenttype = 2;</code>
       */
      public Builder clearContenttype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        contenttype_ = getDefaultInstance().getContenttype();
        onChanged();
        return this;
      }
      /**
       * <code>required string contenttype = 2;</code>
       */
      public Builder setContenttypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        contenttype_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contentstring_ = "";
      /**
       * <code>optional string contentstring = 3;</code>
       */
      public boolean hasContentstring() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string contentstring = 3;</code>
       */
      public java.lang.String getContentstring() {
        java.lang.Object ref = contentstring_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            contentstring_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contentstring = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentstringBytes() {
        java.lang.Object ref = contentstring_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentstring_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contentstring = 3;</code>
       */
      public Builder setContentstring(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        contentstring_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentstring = 3;</code>
       */
      public Builder clearContentstring() {
        bitField0_ = (bitField0_ & ~0x00000004);
        contentstring_ = getDefaultInstance().getContentstring();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentstring = 3;</code>
       */
      public Builder setContentstringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        contentstring_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contentfile_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes contentfile = 4;</code>
       */
      public boolean hasContentfile() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes contentfile = 4;</code>
       */
      public com.google.protobuf.ByteString getContentfile() {
        return contentfile_;
      }
      /**
       * <code>optional bytes contentfile = 4;</code>
       */
      public Builder setContentfile(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        contentfile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes contentfile = 4;</code>
       */
      public Builder clearContentfile() {
        bitField0_ = (bitField0_ & ~0x00000008);
        contentfile_ = getDefaultInstance().getContentfile();
        onChanged();
        return this;
      }

      private java.lang.Object contentfilename_ = "";
      /**
       * <code>optional string contentfilename = 5;</code>
       */
      public boolean hasContentfilename() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string contentfilename = 5;</code>
       */
      public java.lang.String getContentfilename() {
        java.lang.Object ref = contentfilename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            contentfilename_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contentfilename = 5;</code>
       */
      public com.google.protobuf.ByteString
          getContentfilenameBytes() {
        java.lang.Object ref = contentfilename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentfilename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contentfilename = 5;</code>
       */
      public Builder setContentfilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        contentfilename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentfilename = 5;</code>
       */
      public Builder clearContentfilename() {
        bitField0_ = (bitField0_ & ~0x00000010);
        contentfilename_ = getDefaultInstance().getContentfilename();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentfilename = 5;</code>
       */
      public Builder setContentfilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        contentfilename_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object whichphonelocation_ = "";
      /**
       * <code>optional string whichphonelocation = 6;</code>
       */
      public boolean hasWhichphonelocation() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string whichphonelocation = 6;</code>
       */
      public java.lang.String getWhichphonelocation() {
        java.lang.Object ref = whichphonelocation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            whichphonelocation_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string whichphonelocation = 6;</code>
       */
      public com.google.protobuf.ByteString
          getWhichphonelocationBytes() {
        java.lang.Object ref = whichphonelocation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          whichphonelocation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string whichphonelocation = 6;</code>
       */
      public Builder setWhichphonelocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        whichphonelocation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string whichphonelocation = 6;</code>
       */
      public Builder clearWhichphonelocation() {
        bitField0_ = (bitField0_ & ~0x00000020);
        whichphonelocation_ = getDefaultInstance().getWhichphonelocation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string whichphonelocation = 6;</code>
       */
      public Builder setWhichphonelocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        whichphonelocation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sendtowhichpc_ = "";
      /**
       * <code>optional string sendtowhichpc = 7;</code>
       */
      public boolean hasSendtowhichpc() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string sendtowhichpc = 7;</code>
       */
      public java.lang.String getSendtowhichpc() {
        java.lang.Object ref = sendtowhichpc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sendtowhichpc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sendtowhichpc = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSendtowhichpcBytes() {
        java.lang.Object ref = sendtowhichpc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sendtowhichpc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sendtowhichpc = 7;</code>
       */
      public Builder setSendtowhichpc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        sendtowhichpc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sendtowhichpc = 7;</code>
       */
      public Builder clearSendtowhichpc() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sendtowhichpc_ = getDefaultInstance().getSendtowhichpc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sendtowhichpc = 7;</code>
       */
      public Builder setSendtowhichpcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        sendtowhichpc_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object locationstring_ = "";
      /**
       * <code>optional string locationstring = 8;</code>
       */
      public boolean hasLocationstring() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string locationstring = 8;</code>
       */
      public java.lang.String getLocationstring() {
        java.lang.Object ref = locationstring_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            locationstring_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string locationstring = 8;</code>
       */
      public com.google.protobuf.ByteString
          getLocationstringBytes() {
        java.lang.Object ref = locationstring_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locationstring_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string locationstring = 8;</code>
       */
      public Builder setLocationstring(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        locationstring_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string locationstring = 8;</code>
       */
      public Builder clearLocationstring() {
        bitField0_ = (bitField0_ & ~0x00000080);
        locationstring_ = getDefaultInstance().getLocationstring();
        onChanged();
        return this;
      }
      /**
       * <code>optional string locationstring = 8;</code>
       */
      public Builder setLocationstringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        locationstring_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ZhMessage)
    }

    // @@protoc_insertion_point(class_scope:ZhMessage)
    private static final ZhMessageProto.ZhMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ZhMessageProto.ZhMessage();
    }

    public static ZhMessageProto.ZhMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ZhMessage>
        PARSER = new com.google.protobuf.AbstractParser<ZhMessage>() {
      public ZhMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ZhMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ZhMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ZhMessage> getParserForType() {
      return PARSER;
    }

    public ZhMessageProto.ZhMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ZhMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ZhMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ZhMessage.proto\"\300\001\n\tZhMessage\022\016\n\006whoam" +
      "i\030\001 \002(\t\022\023\n\013contenttype\030\002 \002(\t\022\025\n\rcontents" +
      "tring\030\003 \001(\t\022\023\n\013contentfile\030\004 \001(\014\022\027\n\017cont" +
      "entfilename\030\005 \001(\t\022\032\n\022whichphonelocation\030" +
      "\006 \001(\t\022\025\n\rsendtowhichpc\030\007 \001(\t\022\026\n\016location" +
      "string\030\010 \001(\tB\020B\016ZhMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ZhMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ZhMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ZhMessage_descriptor,
        new java.lang.String[] { "Whoami", "Contenttype", "Contentstring", "Contentfile", "Contentfilename", "Whichphonelocation", "Sendtowhichpc", "Locationstring", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
